[package]
name = "bdk_sp_cli_v2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sp-cli2"
path = "src/main.rs"

[dependencies]
bdk_sp = { version = "0.2.0", path = "../../silentpayments/", features = ["serde", "psbt_sp_spend"]}
bdk_file_store = "0.21.0"
bdk_bitcoind_rpc = { version = "0.20.0" }
bdk_coin_select = { version = "0.4.0" }
miniscript = { version = "12.0.0", features = [ "base64" ]}
serde_json = "1.0"
clap = { version = "4.5.17", features = ["derive", "env"] }
anyhow = "1"
serde = "1.0.219"
rand = "0.9.0"
indexer = { version = "0.1.0", path = "../../indexer", features = ["serde"]}
bdk_sp_wallet = { version = "0.1.0", path = "../../wallet", features = ["serde"]}
bdk_sp_oracles = { version = "0.1.0", path = "../../oracles" }
electrum_streaming_client = { git = "https://github.com/sdmg15/electrum_streaming_client", rev = "f8e9178bf2f67af98364363028d909a65d741834", features = ["frigate"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
